import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import "./globals.css";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isDarkMode = true;
  return (
    <html lang="en">
      <body
        className={isDarkMode ? "dark" : ""}
      >

        <ThemeProvider attribute="class">
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
